[default_config]
version = "0.10.0"
assembler = "gas"
instruction_set = "x86"

[default_config.opts]
compiler = "gcc"
compile_flags_txt = [
    '"-no-pie"',
    '" -nostdlib"',
    '"-nostartfiles"',
    '"-m64"',
    '"-g"',
    '"-Wall"',
]
diagnostics = true
default_diagnostics = false
